### ISSUE TITLE
How to release the memory after exporting the video in headless rendering?

### ISSUE THREAD

**Issue by kunkun0w0** [eth-ait/aitviewer#53]
Hi~ I encountered a memory problem when using headless rendering multiple times. The memory occupancy will accumulate till the system shuts down. I tried to reset the viewer and release the renderable nodes after saving the video. However, it does not work.
```
self.viewer = HeadlessRenderer()

def rendering_loop(self, ...):
     self.viewer.reset()
     obj = Skeletons(...)
     self.viewer.scene.add(obj)
     self.viewer.lock_to_node(obj)
     self.viewer.save_video(...)
     obj.release()
```

I checked line by line and found that the memory usage suddenly increased after the `self.viewer.save_video`.

Would you like to give me some suggestions to solve this?

**Comment by kaufManu** [comment]
Yes, I am aware of this unfortunate issue. We think it's due to a memory leak in moderngl-window. The related issue is [here](https://github.com/moderngl/moderngl/issues/512), and although it is closed, the problem does not appear to be fixed according to the latest comments.

Two things help:
- Switching the window type to `pyglet` (see #12 ), but that is less performant.
- Launch the headless rendering in a new _process_ every time you use it. Effectively this means you cannot reuse the headless renderer multiple times (or not too many times, until your system's memory is exceeded). Implementation-wise it's easiest to extract your renderer to a new script which you then call via `subprocess.run`.
